#pragma once
enum ServiceCommands {QUIT, START_NOTIFICATIONS, STOP_NOTIFICATIONS, ADD_RULE, RULE_COUNT, GET_RULE,REMOVE_RULE,LG_FIRST,LG_NEXT,LG_CLOSE,
                      CRRULE_REQUEST,NOTIFICATION
};
#define INVALID_COMMAND 0xFFFFFFFF
enum ServiceErrors {OK, FAIL};
